# Generated by Django 3.2.8 on 2021-10-25 23:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postAndRate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profilePicture'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='postedPhotos'),
        ),
    ]
