# Generated by Django 3.2.8 on 2021-10-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postAndRate', '0002_auto_20211025_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profilePicture',
        ),
    ]
